%% Compute the cross-validated error across lambda_l1 for pl
tic
lambda_l1_pl = exp(linspace(log(0.01), log(10), 10));
loss_l1_pl = zeros(size(lambda_l1_pl));
for i = 1:numel(lambda_l1_pl)
    [~, loss] = infer_ising_approx_l1(X_train,...
      'method', 'pl', ...
      'lambda_l1', lambda_l1_pl(i),...
      'cross_validate', 10);
    loss_l1_pl(i) = loss;
end

% Choose optimal likelihood
opt_l1_pl = lambda_l1_pl(loss_l1_pl == min(loss_l1_pl));
opt_l1_pl = opt_l1_pl(1);

% Infer parameters for optimal lambda
params_pl = infer_ising_approx_l1(X_train,   ...
  'method', 'pl', ...
  'lambda_l1', opt_l1_pl(1),...
  'display', 'iter');
time_pl = toc;

%% Compute the cross-validated error across lambda_l1 for mpf
tic
lambda_l1_mpf = exp(linspace(log(0.01), log(10), 10));
loss_l1_mpf = zeros(size(lambda_l1_mpf));
for i = 1:numel(lambda_l1_mpf)
    disp(['Testing lambda = ' num2str(lambda_l1_mpf(i)) ...
          ': ' num2str(i) ' of ' num2str(numel(lambda_l1_mpf)) '\n'])
    [~, loss] = infer_ising_approx_l1(X_train,...
      'method', 'mpf', ...
      'lambda_l1', lambda_l1_mpf(i),...
      'cross_validate', 10);
    loss_l1_mpf(i) = loss;
end

% Choose optimal likelihood
opt_l1_mpf = lambda_l1_mpf(loss_l1_mpf == min(loss_l1_mpf));
opt_l1_mpf = opt_l1_mpf(1);

% Infer parameters for optimal lambda
params_mpf = infer_ising_approx_l1(X_train,   ...
  'method', 'mpf', ...
  'lambda_l1', opt_l1_mpf,...
  'display', 'iter');
time_mpf = toc;

%% Pseudolikelihood decimation
params_pld = infer_ising_decimation(X_train,...
  'method',   'pl',  ...
  'lambda_l1',   0,  ...
  'display', 'iter');

%% Persistent Contrastive Divergence + L1
fprintf('PCD\n');
tic
params_pcd = infer_ising_pcd(X_train,...
  'lambda_l1',      opt_l1_pl,     ...
  'num_iterations', 5E4,           ...
  'num_particles',  100,           ...
  'num_gsweeps',      3,           ...
  'plot', 'off');
time_pcd = toc;

%%
fprintf('BBSVI\n');
tic
params_bbsvi = infer_ising_bbsvi(X_train, ...
  'scale_laplacian',  1 / (N_sample * opt_l1_pl), ...
  'var_h',  0,                                    ...
  'var_J',  0,                                    ...
  'num_iterations', 5E4,                          ...
  'num_particles', 100,                           ...
  'num_samples',     3,                           ...
  'num_gsweeps',     3,                           ...
  'plot', 'off');
time_bbsvi = toc;

%% Centered Horsehose
fprintf('Centered\n');
tic
params_centered = infer_ising_centered(X_train,...
  'num_iterations', 5E4,     ...
  'num_particles',  100,     ...
  'num_samples',     3,      ...
  'num_gsweeps',     3,      ...
  'hyperprior', 'horseshoe', ...
  'plot', 'off');
time_centered = toc;

%% Fadeout
fprintf('Fadeout\n');
tic
params_fadeout = infer_ising_fadeout(X_train,...
  'num_iterations', 5E4,     ...
  'num_particles',  100,     ...
  'num_samples',      3,     ...
  'num_gsweeps',      3,     ...
  'hyperprior', 'horseshoe', ...
  'plot', 'off');
time_fadeout = toc;